services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    ports:
      - "8222:80"
    volumes:
      - ${HOMELAB_ROOT}/data/vaultwarden:/data
    environment:
      - DOMAIN=http://${LAN_IP}:8222
      - SIGNUPS_ALLOWED=true
      - ADMIN_TOKEN=5YeirC2iiS1i_w0Pj1FF2nQIkh2fZwCVHKTzKTMfkh-WwXpzGQmNYbZ0LKHl6WnaNCnyiVO7nJ0hMrJp6sBK-Q
      - WEBSOCKET_ENABLED=true
    networks:
      - homelab

networks:
  homelab:
    external: true
