services:
  tandoor-db:
    image: postgres:16-alpine
    container_name: tandoor-db
    restart: unless-stopped
    volumes:
      - ${HOMELAB_ROOT}/data/tandoor/db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: djangodb
      POSTGRES_USER: djangouser
      POSTGRES_PASSWORD: ${TANDOOR_DB_PASSWORD:?defini TANDOOR_DB_PASSWORD en .env}
    networks:
      - homelab

  tandoor-web:
    image: vabene1111/recipes:latest
    container_name: tandoor-web
    restart: unless-stopped
    depends_on:
      - tandoor-db
    ports:
      - "3030:80"
    volumes:
      - ${HOMELAB_ROOT}/data/tandoor/mediafiles:/opt/recipes/mediafiles
      - tandoor_staticfiles:/opt/recipes/staticfiles
    environment:
      - SECRET_KEY=${TANDOOR_SECRET_KEY:?defini TANDOOR_SECRET_KEY en .env}
      - DB_ENGINE=django.db.backends.postgresql
      - POSTGRES_HOST=tandoor-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=djangouser
      - POSTGRES_PASSWORD=${TANDOOR_DB_PASSWORD:?defini TANDOOR_DB_PASSWORD en .env}
      - POSTGRES_DB=djangodb
      - ALLOWED_HOSTS=${LAN_IP},localhost,127.0.0.1
      - TIMEZONE=America/Santiago
    networks:
      - homelab

volumes:
  tandoor_staticfiles:

networks:
  homelab:
    external: true
