services:
  bookorbit:
    image: ghcr.io/bookorbit/bookorbit:latest
    container_name: bookorbit
    init: true
    restart: unless-stopped
    ports:
      - "3020:3000"
    environment:
      NODE_ENV: production
      PORT: 3000
      APP_URL: http://192.168.1.2:3020
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: bookorbit
      POSTGRES_PASSWORD: ae4df635212660504655979ac9f0f999aefd58e2f3854406
      POSTGRES_DB: bookorbit
      JWT_SECRET: 6247109f3195548d5c6f5ae962ea674bf972ad1f22e5c4994c5ab53f2c2f71e0
      SETUP_BOOTSTRAP_TOKEN: 2baf710184c1581a60df9b69abb93bcb
      LIBRARY_BROWSE_ROOT: /books
      NODE_MAX_OLD_SPACE_SIZE: 2048
      PUID: 1000
      PGID: 1000
    volumes:
      - /home/pipeaalzamora/homelab/media:/books
      - /home/pipeaalzamora/homelab/data/reading/bookorbit:/data
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - homelab

  postgres:
    image: pgvector/pgvector:pg18
    container_name: bookorbit-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: bookorbit
      POSTGRES_PASSWORD: ae4df635212660504655979ac9f0f999aefd58e2f3854406
      POSTGRES_DB: bookorbit
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/pipeaalzamora/homelab/data/reading/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bookorbit -d bookorbit"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - homelab

  readeck:
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck
    restart: unless-stopped
    ports:
      - "3025:8000"
    environment:
      - READECK_SERVER_HOST=0.0.0.0
      - READECK_SERVER_PORT=8000
      - READECK_SERVER_PREFIX=/
      - READECK_ALLOWED_HOSTS=192.168.1.2,localhost
    volumes:
      - /home/pipeaalzamora/homelab/data/reading/readeck:/readeck
    networks:
      - homelab

networks:
  homelab:
    external: true
