---
# =============================================================
# Homepage — Configuración general
# =============================================================

title: Homelab — Pipe Edition
description: Panel local del servidor familiar
favicon: https://raw.githubusercontent.com/gethomepage/homepage/main/public/apple-touch-icon.png
theme: dark
color: slate

headerStyle: clean
hideVersion: true
useEqualHeights: true

layout:
  🔒 Core:
    style: row
    columns: 2
  🎬 Media:
    style: row
    columns: 8
  📝 Productividad:
    style: row
    columns: 3
