#!/usr/bin/env bash
# =============================================================
# Genera env/.env para pruebas locales.
# No imprime secretos en pantalla.
# =============================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$ROOT_DIR/env/.env"

if [[ -f "$ENV_FILE" ]]; then
  echo "env/.env ya existe. No se sobreescribe."
  exit 0
fi

rand_hex() {
  openssl rand -hex "$1"
}

rand_b64() {
  openssl rand -base64 "$1" | tr -d '\n'
}

cat > "$ENV_FILE" <<EOF
TZ=America/Santiago
PUID=1000
PGID=1000
HOMELAB_ROOT=/home/pipeaalzamora/homelab
LOCAL_DOMAIN=home
NPM_HTTP_PORT=8088
NPM_HTTPS_PORT=8443
NPM_ADMIN_PORT=8181
ADGUARD_DNS_PORT=1053
ADGUARD_SETUP_PORT=3000
ADGUARD_ADMIN_PORT=8080
HOMEPAGE_ALLOWED_HOSTS=localhost:3001,127.0.0.1:3001
ADGUARD_USERNAME=pipe
ADGUARD_PASSWORD=$(rand_b64 24)

TAILSCALE_AUTHKEY=

NEXTCLOUD_ADMIN_USER=pipe
NEXTCLOUD_ADMIN_PASSWORD=$(rand_b64 24)
NEXTCLOUD_DB_ROOT_PASSWORD=$(rand_b64 24)
NEXTCLOUD_DB_PASSWORD=$(rand_b64 24)
NEXTCLOUD_TRUSTED_DOMAINS='cloud.home homelab-pipe localhost'

QBITTORRENT_USERNAME=admin
QBITTORRENT_PASSWORD=$(rand_b64 18)

FORGEJO_DB_PASSWORD=$(rand_b64 24)
FORGEJO_DOMAIN=localhost
FORGEJO_ROOT_URL=http://localhost:3004/
FORGEJO_SSH_DOMAIN=localhost
FORGEJO_SECRET_KEY=$(rand_hex 32)
FORGEJO_INTERNAL_TOKEN=$(rand_hex 32)

BOOKSTACK_DB_PASSWORD=$(rand_b64 24)
BOOKSTACK_APP_KEY=base64:$(rand_b64 32)
BOOKSTACK_APP_URL=http://localhost:6875

N8N_DB_PASSWORD=$(rand_b64 24)
N8N_ENCRYPTION_KEY=$(rand_hex 24)
N8N_BASIC_AUTH_USER=pipe
N8N_BASIC_AUTH_PASSWORD=$(rand_b64 24)

RESTIC_REPOSITORY=local:/mnt/restic-repo
RESTIC_PASSWORD=$(rand_b64 32)
B2_ACCOUNT_ID=
B2_ACCOUNT_KEY=

FACTO_DB_ROOT_PASSWORD=$(rand_b64 24)
FACTO_DB_PASSWORD=$(rand_b64 24)
FACTO_SECRET=$(rand_hex 32)
FACTO_PORT=8086

PIGA_DB_ROOT_PASSWORD=$(rand_b64 24)
PIGA_DB_PASSWORD=$(rand_b64 24)
PIGA_SECRET=$(rand_hex 32)
PIGA_PORT=8087

DOCAT_PORT=8089
DOCAT_MAX_UPLOAD_SIZE=100M

EVERYDOCS_DB_ROOT_PASSWORD=$(rand_b64 24)
EVERYDOCS_DB_PASSWORD=$(rand_b64 24)
EVERYDOCS_SECRET_KEY_BASE=$(rand_hex 64)
EVERYDOCS_IMAGE_TAG=1.5.0
EVERYDOCS_WEB_IMAGE_TAG=1.5.0
EVERYDOCS_WEB_PORT=8090
EVERYDOCS_CORE_PORT=8091

DAILYTXT_IMAGE_TAG=2.6.2
DAILYTXT_SECRET_TOKEN=$(rand_b64 32)
DAILYTXT_ADMIN_PASSWORD=$(rand_b64 24)
DAILYTXT_ALLOW_REGISTRATION=true
DAILYTXT_LOGOUT_AFTER_DAYS=40
DAILYTXT_INDENT=4
DAILYTXT_PORT=8092

WASTEBIN_IMAGE_TAG=latest
WASTEBIN_PORT=8093
WASTEBIN_DATABASE_PATH=/data/state.db
WASTEBIN_BASE_URL=http://localhost:8093
WASTEBIN_PASSWORD_SALT=$(rand_b64 32)
WASTEBIN_SIGNING_KEY=$(rand_b64 64)
WASTEBIN_THEME=ayu
WASTEBIN_TITLE=Wastebin

IGUANA_GIT_REF=master
IGUANA_IMAGE_TAG=local
IGUANA_VARIANT=production
IGUANA_USE_NGINX=true
IGUANA_LANG=es-cl
IGUANA_PORT=8094

AUTHELIA_JWT_SECRET=$(rand_hex 32)
AUTHELIA_SESSION_SECRET=$(rand_hex 32)
AUTHELIA_STORAGE_ENCRYPTION_KEY=$(rand_hex 32)
AUTHELIA_PORT=9091
EOF

chmod 600 "$ENV_FILE"
echo "env/.env generado."
